export const enum RouterName {
  Home = "/home",
  Info = "/dashboard",
  Song = "/song",
  SongDetail = "/songDetail",
  Singer = "/singer",
  SongList = "/songList",
  ListSong = "/listSong",
  Comment = "/comment",
  CommentDetail = "/commentDetail",
  Consumer = "/consumer",
  Collect = "/collect",
  CollectDetail = "/collectDetail",
  Error = "/404",
  SignIn = "/login",
  SignOut = "0",
}
