/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JezerAside: typeof import('./src/components/layout/JezerAside.vue')['default']
    JezerHeader: typeof import('./src/components/layout/JezerHeader.vue')['default']
    JezerHome: typeof import('./src/components/layout/JezerHome.vue')['default']
    JezerIndex: typeof import('@/views/IndexPage.vue')['default']
    JezerLogin: typeof import('./src/components/JezerLogin.vue')['default']
    JezerPlayer: typeof import('./src/components/layout/JezerPlayer.vue')['default']
    JezerSearch: typeof import('./src/components/JezerSearch.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
