/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    JezerAside: typeof import('./src/components/layout/JezerAside.vue')['default']
    JezerComment: typeof import('./src/components/JezerComment.vue')['default']
    JezerCurrentPlay: typeof import('./src/components/JezerCurrentPlay.vue')['default']
    JezerHeader: typeof import('./src/components/layout/JezerHeader.vue')['default']
    JezerMusic: typeof import('./src/components/JezerMusic.vue')['default']
    JezerPlayer: typeof import('./src/components/layout/JezerPlayer.vue')['default']
    JezerPlaylist: typeof import('./src/components/JezerPlaylist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
